import './globals.css'
import { SolanaProvider } from '@/components/solana/solana-provider'
import { ReactQueryProvider } from './react-query-provider'
import { Toaster } from "@/components/ui/sonner"

export const metadata = {
  title: 'Juppaymentgateway',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
            <SolanaProvider>
                {children}
              <Toaster />
            </SolanaProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
